### ISSUE TITLE
Le removeValuesWhere du NiceBaseListCubit ne fait pas ce qu'il dit

### ISSUE THREAD

**Issue by ClovisProvost** [Recursyve/nice_flutter_kit#52]
En ce moment, la fonctione fait un where avec le filter, ce qui garde seulement les éléments où le call back retourne vrai, ce qui est le contraire de ce que le nom de la fonction et le commentaire implique. Il faudrait changer le nom de la fonction pour quelque chose comme `filterWhere` ou changer le code pour faire `state.values.whereNot` 

Le code actuel:

```dart
/// Removes the [NiceBaseListState.values] where the [filter] callback return true.
  void removeValuesWhere(bool Function(D value) filter) {
    final filteredValues = state.values.where(filter).toList(growable: false);
    setValues(filteredValues);
  }
```

**Comment by Jtplouffe** [comment]
Fixed by #53, available in `2.0.1`.
